spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            clientSecret:
          google:
            client-id: 
            clientSecret: